"""add_canonical_answer_and_question_performance

Revision ID: 25d2b9dc70be
Revises: f911293af21c
Create Date: 2026-05-24 10:16:07.494763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d2b9dc70be'
down_revision: Union[str, Sequence[str], None] = 'f911293af21c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('total_duration_ms', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'user_id', 'question_id', name='uq_qperf_test_user_question')
    )
    op.create_index('ix_qperf_test_question', 'question_performance', ['test_id', 'question_id'], unique=False)
    op.create_index('ix_qperf_test_user', 'question_performance', ['test_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_question_performance_id'), 'question_performance', ['id'], unique=False)
    op.add_column('attempt_answers', sa.Column('canonical_answer_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempt_answers', 'canonical_answer_index')
    op.drop_index(op.f('ix_question_performance_id'), table_name='question_performance')
    op.drop_index('ix_qperf_test_user', table_name='question_performance')
    op.drop_index('ix_qperf_test_question', table_name='question_performance')
    op.drop_table('question_performance')
    # ### end Alembic commands ###
