"""add_perf_indexes

Revision ID: f911293af21c
Revises: a8b5c3d7e9f1
Create Date: 2026-05-23 18:52:50.622465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f911293af21c'
down_revision: Union[str, Sequence[str], None] = 'a8b5c3d7e9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_attempts_status_started', 'attempts', ['status', 'started_at'], unique=False)
    op.create_index('ix_attempts_test_status_started', 'attempts', ['test_id', 'status', 'started_at'], unique=False)
    op.create_index('ix_change_requests_collection_created', 'change_requests', ['test_collection_id', 'created_at'], unique=False)
    op.create_index('ix_sessions_active_expires', 'sessions', ['is_active', 'expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index('ix_test_collections_access_owner', 'test_collections', ['access_level', 'owner_id'], unique=False)
    op.create_index('ix_test_shares_collection_user', 'test_shares', ['test_collection_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_test_shares_test_collection_id'), 'test_shares', ['test_collection_id'], unique=False)
    op.create_index(op.f('ix_test_shares_user_id'), 'test_shares', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_shares_user_id'), table_name='test_shares')
    op.drop_index(op.f('ix_test_shares_test_collection_id'), table_name='test_shares')
    op.drop_index('ix_test_shares_collection_user', table_name='test_shares')
    op.drop_index('ix_test_collections_access_owner', table_name='test_collections')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_active_expires', table_name='sessions')
    op.drop_index('ix_change_requests_collection_created', table_name='change_requests')
    op.drop_index('ix_attempts_test_status_started', table_name='attempts')
    op.drop_index('ix_attempts_status_started', table_name='attempts')
    # ### end Alembic commands ###
